# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160915_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
