# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160916_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
