# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_business_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='psic_class',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
