# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_psic_class_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='business',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='business',
            name='year',
            field=models.IntegerField(default=2016, max_length=4, verbose_name='Year Issued'),
        ),
    ]
