# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161108_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='year',
            field=models.IntegerField(default=2016, verbose_name='Year Issued'),
        ),
    ]
