# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161108_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Partnership'), (3, 'Corporation'), (4, 'Cooperative'), (5, 'Workers Association/Labor Union')], null=True, verbose_name='Type of Business'),
        ),
        migrations.AddField(
            model_name='business',
            name='ownership_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Filipino'), (2, 'Philippine-Foreign Joint Venture'), (3, 'Foreign')], null=True, verbose_name='Type of Business Ownership'),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
