# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161202_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector_DTI_NCCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Sector From DTI-NCCP',
                'verbose_name_plural': 'Sectors From DTI-NCCP',
            },
        ),
        migrations.CreateModel(
            name='Sector_DTI_NCCP_Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('sector_dti_nccp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sector_DTI_NCCP')),
            ],
            options={
                'verbose_name': 'DTI-NCCP Sectors Dataset',
                'verbose_name_plural': 'DTI-NCCP Sectors Datasets',
            },
        ),
        migrations.RenameModel(
            old_name='Sector',
            new_name='Sector_DTI_Files',
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Line of Business', 'verbose_name_plural': 'Line of Business'},
        ),
        migrations.AlterModelOptions(
            name='sector_dti_files',
            options={'verbose_name': 'Sector From DTI Files', 'verbose_name_plural': 'Sectors From DTI Files'},
        ),
        migrations.RemoveField(
            model_name='business',
            name='sector',
        ),
        migrations.AddField(
            model_name='business',
            name='sector_dti_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sector_DTI_Files', verbose_name='Sector from DTI Files'),
        ),
        migrations.AlterField(
            model_name='business',
            name='capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Asset Size'),
        ),
        migrations.AddField(
            model_name='business',
            name='sector_dti_nccp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sector_DTI_NCCP', verbose_name='Sector from DTI-NCCP'),
        ),
    ]
